# Data Encoding - Converting categorical values into a numerical format


### One Hot Encoding(HOE) or Nominal Encoding

 each category is represented as a binary vector where each bit corresponds to a unique category.ie convert each category into a new binary column .

if you one feature has 1000 categories,then 1000 new binary feature(column) will be created.

Resulting dataset is a Sparse, b'coz most of the entries are Zeros (with only one 1/row for each category). so it leades to  overfitting issue

In [21]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import seaborn as sns

In [2]:
#create a df
df=pd.DataFrame(
    {
        'color':['red','blue','green','green','red','blue']
    }
)

In [3]:
df.head()

color
0    red
1   blue
2  green
3  green
4    red

In [8]:
#create an instance of ONE hot encoder

encoder=OneHotEncoder()

#perform fit and trandsform
encoder.fit_transform(df[['color']]) # fits the OneHotEncoder on the color column of the df DataFrame and then transforms it into a sparse matrix.

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [9]:
#convert to an array
encoded_values=encoder.fit_transform(df[['color']]).toarray()
encoded_values

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [15]:
encoded_df=pd.DataFrame(encoded_values,columns=encoder.get_feature_names_out())
encoded_df

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

The columns are named using encoder.get_feature_names_out(), which generates appropriate column names based on the original column names and the categories.

In [18]:
pd.concat([df,encoded_df],axis=1)

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

The original DataFrame df is concatenated with encoded_df along the columns (axis=1), resulting in a new DataFrame that contains both the original data and the one-hot encoded columns

In [20]:
#for new data 
encoder.transform([['blue']]).toarray()

/Users/ashikacherikkaparambath/Desktop/Datascience/venv/lib/python3.9/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

transforms a new data point (in this case, [['blue']]) using the already-fitted encoder.

### convert tips datset to numerical format

In [24]:
df2=sns.load_dataset('tips')
df2

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

we need to convert categorical features like sex,smoker,day,and time 

In [36]:
tips_encodedValues=encoder.fit_transform(df2[['sex','smoker','day','time']]).toarray()
tips_encodedValues

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]])

In [34]:
tips_encoded=pd.DataFrame(tips_encodedValues,columns=encoder.get_feature_names_out())
tips_encoded

sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
1           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
2           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
3           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
4           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
..          ...       ...        ...         ...      ...      ...      ...   
239         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
240         1.0       0.0        0.0         1.0      0.0      1.0      0.0   
241         0.0       1.0        0.0         1.0      0.0      1.0      0.0   
242         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
243         1.0       0.0        1.0         0.0      0.0      0.0      0.0   

     day_Thur  time_Dinner  time_Lunch  
0         0.0          1.0         0.0  
1         0.0          1.0         0.0  
2         0.0          1.0         0.0  
3         0.0          1.0         0.0  
4         0.0          1.0         0.0  
..        ...          ...         ...  
239       0.0          1.0         0.0  
240       0.0          1.0         0.0  
241       0.0          1.0         0.0  
242       0.0          1.0         0.0  
243       1.0          1.0         0.0  

[244 rows x 10 columns]

In [38]:
pd.concat([df2,tips_encoded],axis=1)

total_bill   tip     sex smoker   day    time  size  sex_Female  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0   
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0   
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0   
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0   
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0   
..          ...   ...     ...    ...   ...     ...   ...         ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0   

     sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  day_Thur  \
0         0.0        1.0         0.0      0.0      0.0      1.0       0.0   
1         1.0        1.0         0.0      0.0      0.0      1.0       0.0   
2         1.0        1.0         0.0      0.0      0.0      1.0       0.0   
3         1.0        1.0         0.0      0.0      0.0      1.0       0.0   
4         0.0        1.0         0.0      0.0      0.0      1.0       0.0   
..        ...        ...         ...      ...      ...      ...       ...   
239       1.0        1.0         0.0      0.0      1.0      0.0       0.0   
240       0.0        0.0         1.0      0.0      1.0      0.0       0.0   
241       1.0        0.0         1.0      0.0      1.0      0.0       0.0   
242       1.0        1.0         0.0      0.0      1.0      0.0       0.0   
243       0.0        1.0         0.0      0.0      0.0      0.0       1.0   

     time_Dinner  time_Lunch  
0            1.0         0.0  
1            1.0         0.0  
2            1.0         0.0  
3            1.0         0.0  
4            1.0         0.0  
..           ...         ...  
239          1.0         0.0  
240          1.0         0.0  
241          1.0         0.0  
242          1.0         0.0  
243          1.0         0.0  

[244 rows x 17 columns]